# ==== Login view ====

login_title_generic= Hola
login_subtitle_phrase= Listo para cortar historia.
login_prompt_pin= Ingresar PIN
login_error_pin_invalid= PIN invalido
login_button_enter= Ingresar

# ==== Payment methods ====
payment_method_cash=Efectivo
payment_method_transfer=Transferencia
payment_method_card=Tarjeta
payment_method_qr=QR
payment_method_other=Otro